package models

// Code generated by ksql.
// Do'nt Edit!!!
// Do'nt Edit!!!
// Do'nt Edit!!!
//
// from database: kman
// table:         operator
// orm version:   1.0.5
// created time:  2025-05-13 17:26:03
/**
Table DDL:
CREATE TABLE `operator` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(31) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` varchar(64) NOT NULL DEFAULT '' COMMENT '密码',
  `create_time` bigint NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` bigint NOT NULL DEFAULT '0' COMMENT '更新时间',
  `permissions` json NOT NULL COMMENT '权限',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0 - 正常 1 - 禁用',
  `project_id` int NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username_UNIQUE` (`project_id`,`username`),
  KEY `idx_project` (`project_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
*/

import (
	"context"

	"github.com/kovey/db-go/v3"
	"github.com/kovey/db-go/v3/model"
)

const (
	Table_Operator             = "operator"    //
	Table_Operator_CreateTime  = "create_time" // 创建时间
	Table_Operator_Id          = "id"          //
	Table_Operator_Password    = "password"    // 密码
	Table_Operator_Permissions = "permissions" // 权限
	Table_Operator_ProjectId   = "project_id"  // 项目ID
	Table_Operator_Status      = "status"      // 状态 0 - 正常 1 - 禁用
	Table_Operator_UpdateTime  = "update_time" // 更新时间
	Table_Operator_Username    = "username"    // 用户名
)

type Operator struct {
	*model.Model `db:"-" json:"-"` // model
	CreateTime   int64             `db:"create_time" json:"create_time"` // 创建时间
	Id           int64             `db:"id" json:"id"`                   //
	Password     string            `db:"password" json:"password"`       // 密码
	Permissions  string            `db:"permissions" json:"permissions"` // 权限
	ProjectId    int               `db:"project_id" json:"project_id"`   // 项目ID
	Status       int8              `db:"status" json:"status"`           // 状态 0 - 正常 1 - 禁用
	UpdateTime   int64             `db:"update_time" json:"update_time"` // 更新时间
	Username     string            `db:"username" json:"username"`       // 用户名
}

func NewOperator() *Operator {
	return &Operator{Model: model.NewModel(Table_Operator, Table_Operator_Id, model.Type_Int)}
}

func (self *Operator) Save(ctx context.Context) error {
	return self.Model.Save(ctx, self)
}

func (self *Operator) Clone() ksql.RowInterface {
	return NewOperator()
}

func (self *Operator) Values() []any {
	return []any{&self.CreateTime, &self.Id, &self.Password, &self.Permissions, &self.ProjectId, &self.Status, &self.UpdateTime, &self.Username}
}

func (self *Operator) Columns() []string {
	return []string{Table_Operator_CreateTime, Table_Operator_Id, Table_Operator_Password, Table_Operator_Permissions, Table_Operator_ProjectId, Table_Operator_Status, Table_Operator_UpdateTime, Table_Operator_Username}
}

func (self *Operator) Delete(ctx context.Context) error {
	return self.Model.Delete(ctx, self)
}

func (self *Operator) Query() ksql.BuilderInterface[*Operator] {
	return model.Row(self)
}
