// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: operator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ProjectId     int32                  `protobuf:"varint,3,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorAddReq) Reset() {
	*x = OperatorAddReq{}
	mi := &file_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorAddReq) ProtoMessage() {}

func (x *OperatorAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorAddReq.ProtoReflect.Descriptor instead.
func (*OperatorAddReq) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorAddReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OperatorAddReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OperatorAddReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *OperatorAddReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type OperatorAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorAddResp) Reset() {
	*x = OperatorAddResp{}
	mi := &file_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorAddResp) ProtoMessage() {}

func (x *OperatorAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorAddResp.ProtoReflect.Descriptor instead.
func (*OperatorAddResp) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{1}
}

type OperatorEditReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId     int32                  `protobuf:"varint,5,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorEditReq) Reset() {
	*x = OperatorEditReq{}
	mi := &file_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorEditReq) ProtoMessage() {}

func (x *OperatorEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorEditReq.ProtoReflect.Descriptor instead.
func (*OperatorEditReq) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{2}
}

func (x *OperatorEditReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OperatorEditReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OperatorEditReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperatorEditReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OperatorEditReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type OperatorEditResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorEditResp) Reset() {
	*x = OperatorEditResp{}
	mi := &file_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorEditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorEditResp) ProtoMessage() {}

func (x *OperatorEditResp) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorEditResp.ProtoReflect.Descriptor instead.
func (*OperatorEditResp) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{3}
}

type OperatorListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId     int32                  `protobuf:"varint,5,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorListReq) Reset() {
	*x = OperatorListReq{}
	mi := &file_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorListReq) ProtoMessage() {}

func (x *OperatorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorListReq.ProtoReflect.Descriptor instead.
func (*OperatorListReq) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{4}
}

func (x *OperatorListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OperatorListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OperatorListReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OperatorListReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OperatorListReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type OperatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Permissions   []int64                `protobuf:"varint,3,rep,packed,name=permissions,proto3" json:"permissions,omitempty"`
	CreateTime    string                 `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorInfo) Reset() {
	*x = OperatorInfo{}
	mi := &file_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorInfo) ProtoMessage() {}

func (x *OperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorInfo.ProtoReflect.Descriptor instead.
func (*OperatorInfo) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{5}
}

func (x *OperatorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperatorInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OperatorInfo) GetPermissions() []int64 {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *OperatorInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type OperatorListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalPage     int64                  `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	TotalCount    int64                  `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	List          []*OperatorInfo        `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorListResp) Reset() {
	*x = OperatorListResp{}
	mi := &file_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorListResp) ProtoMessage() {}

func (x *OperatorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorListResp.ProtoReflect.Descriptor instead.
func (*OperatorListResp) Descriptor() ([]byte, []int) {
	return file_operator_proto_rawDescGZIP(), []int{6}
}

func (x *OperatorListResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OperatorListResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OperatorListResp) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *OperatorListResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *OperatorListResp) GetList() []*OperatorInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_operator_proto protoreflect.FileDescriptor

const file_operator_proto_rawDesc = "" +
	"\n" +
	"\x0eoperator.proto\"\x82\x01\n" +
	"\x0eOperatorAddReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1c\n" +
	"\tprojectId\x18\x03 \x01(\x05R\tprojectId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"\x11\n" +
	"\x0fOperatorAddResp\"\x93\x01\n" +
	"\x0fOperatorEditReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tprojectId\x18\x05 \x01(\x05R\tprojectId\"\x12\n" +
	"\x10OperatorEditResp\"\x97\x01\n" +
	"\x0fOperatorListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tprojectId\x18\x05 \x01(\x05R\tprojectId\"|\n" +
	"\fOperatorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12 \n" +
	"\vpermissions\x18\x03 \x03(\x03R\vpermissions\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\tR\n" +
	"createTime\"\xa3\x01\n" +
	"\x10OperatorListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1c\n" +
	"\ttotalPage\x18\x03 \x01(\x03R\ttotalPage\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x04 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\x04list\x18\x05 \x03(\v2\r.OperatorInfoR\x04list2\x94\x01\n" +
	"\bOperator\x12*\n" +
	"\x03Add\x12\x0f.OperatorAddReq\x1a\x10.OperatorAddResp\"\x00\x12-\n" +
	"\x04Edit\x12\x10.OperatorEditReq\x1a\x11.OperatorEditResp\"\x00\x12-\n" +
	"\x04List\x12\x10.OperatorListReq\x1a\x11.OperatorListResp\"\x00B\tZ\a./protob\x06proto3"

var (
	file_operator_proto_rawDescOnce sync.Once
	file_operator_proto_rawDescData []byte
)

func file_operator_proto_rawDescGZIP() []byte {
	file_operator_proto_rawDescOnce.Do(func() {
		file_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operator_proto_rawDesc), len(file_operator_proto_rawDesc)))
	})
	return file_operator_proto_rawDescData
}

var file_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_operator_proto_goTypes = []any{
	(*OperatorAddReq)(nil),   // 0: OperatorAddReq
	(*OperatorAddResp)(nil),  // 1: OperatorAddResp
	(*OperatorEditReq)(nil),  // 2: OperatorEditReq
	(*OperatorEditResp)(nil), // 3: OperatorEditResp
	(*OperatorListReq)(nil),  // 4: OperatorListReq
	(*OperatorInfo)(nil),     // 5: OperatorInfo
	(*OperatorListResp)(nil), // 6: OperatorListResp
}
var file_operator_proto_depIdxs = []int32{
	5, // 0: OperatorListResp.list:type_name -> OperatorInfo
	0, // 1: Operator.Add:input_type -> OperatorAddReq
	2, // 2: Operator.Edit:input_type -> OperatorEditReq
	4, // 3: Operator.List:input_type -> OperatorListReq
	1, // 4: Operator.Add:output_type -> OperatorAddResp
	3, // 5: Operator.Edit:output_type -> OperatorEditResp
	6, // 6: Operator.List:output_type -> OperatorListResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operator_proto_init() }
func file_operator_proto_init() {
	if File_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_proto_rawDesc), len(file_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_proto_goTypes,
		DependencyIndexes: file_operator_proto_depIdxs,
		MessageInfos:      file_operator_proto_msgTypes,
	}.Build()
	File_operator_proto = out.File
	file_operator_proto_goTypes = nil
	file_operator_proto_depIdxs = nil
}
