// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nodes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeEditReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Weight        int64                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId     int32                  `protobuf:"varint,4,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEditReq) Reset() {
	*x = NodeEditReq{}
	mi := &file_nodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEditReq) ProtoMessage() {}

func (x *NodeEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEditReq.ProtoReflect.Descriptor instead.
func (*NodeEditReq) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{0}
}

func (x *NodeEditReq) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeEditReq) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NodeEditReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeEditReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type NodeEditResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEditResp) Reset() {
	*x = NodeEditResp{}
	mi := &file_nodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEditResp) ProtoMessage() {}

func (x *NodeEditResp) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEditResp.ProtoReflect.Descriptor instead.
func (*NodeEditResp) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{1}
}

type NodeDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId     int32                  `protobuf:"varint,3,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeleteReq) Reset() {
	*x = NodeDeleteReq{}
	mi := &file_nodes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeleteReq) ProtoMessage() {}

func (x *NodeDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeleteReq.ProtoReflect.Descriptor instead.
func (*NodeDeleteReq) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{2}
}

func (x *NodeDeleteReq) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeDeleteReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeDeleteReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type NodeDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeleteResp) Reset() {
	*x = NodeDeleteResp{}
	mi := &file_nodes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeleteResp) ProtoMessage() {}

func (x *NodeDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeleteResp.ProtoReflect.Descriptor instead.
func (*NodeDeleteResp) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{3}
}

type NodeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId     int32                  `protobuf:"varint,5,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListReq) Reset() {
	*x = NodeListReq{}
	mi := &file_nodes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListReq) ProtoMessage() {}

func (x *NodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListReq.ProtoReflect.Descriptor instead.
func (*NodeListReq) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{4}
}

func (x *NodeListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *NodeListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *NodeListReq) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeListReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeListReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Weight        int64                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Host          string                 `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,8,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nodes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *NodeInfo) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type NodeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalPage     int64                  `protobuf:"varint,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	TotalCount    int64                  `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	List          []*NodeInfo            `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResp) Reset() {
	*x = NodeListResp{}
	mi := &file_nodes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResp) ProtoMessage() {}

func (x *NodeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResp.ProtoReflect.Descriptor instead.
func (*NodeListResp) Descriptor() ([]byte, []int) {
	return file_nodes_proto_rawDescGZIP(), []int{6}
}

func (x *NodeListResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *NodeListResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *NodeListResp) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *NodeListResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NodeListResp) GetList() []*NodeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_nodes_proto protoreflect.FileDescriptor

const file_nodes_proto_rawDesc = "" +
	"\n" +
	"\vnodes.proto\"u\n" +
	"\vNodeEditReq\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x03R\x06weight\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tprojectId\x18\x04 \x01(\x05R\tprojectId\"\x0e\n" +
	"\fNodeEditResp\"_\n" +
	"\rNodeDeleteReq\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tprojectId\x18\x03 \x01(\x05R\tprojectId\"\x10\n" +
	"\x0eNodeDeleteResp\"\x8d\x01\n" +
	"\vNodeListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tprojectId\x18\x05 \x01(\x05R\tprojectId\"\xc8\x01\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x03R\x06weight\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\b \x01(\tR\x04port\"\x9b\x01\n" +
	"\fNodeListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1c\n" +
	"\ttotalPage\x18\x03 \x01(\x03R\ttotalPage\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x04 \x01(\x03R\n" +
	"totalCount\x12\x1d\n" +
	"\x04list\x18\x05 \x03(\v2\t.NodeInfoR\x04list2\x81\x01\n" +
	"\x04Node\x12%\n" +
	"\x04Edit\x12\f.NodeEditReq\x1a\r.NodeEditResp\"\x00\x12+\n" +
	"\x06Delete\x12\x0e.NodeDeleteReq\x1a\x0f.NodeDeleteResp\"\x00\x12%\n" +
	"\x04List\x12\f.NodeListReq\x1a\r.NodeListResp\"\x00B\tZ\a./protob\x06proto3"

var (
	file_nodes_proto_rawDescOnce sync.Once
	file_nodes_proto_rawDescData []byte
)

func file_nodes_proto_rawDescGZIP() []byte {
	file_nodes_proto_rawDescOnce.Do(func() {
		file_nodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodes_proto_rawDesc), len(file_nodes_proto_rawDesc)))
	})
	return file_nodes_proto_rawDescData
}

var file_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nodes_proto_goTypes = []any{
	(*NodeEditReq)(nil),    // 0: NodeEditReq
	(*NodeEditResp)(nil),   // 1: NodeEditResp
	(*NodeDeleteReq)(nil),  // 2: NodeDeleteReq
	(*NodeDeleteResp)(nil), // 3: NodeDeleteResp
	(*NodeListReq)(nil),    // 4: NodeListReq
	(*NodeInfo)(nil),       // 5: NodeInfo
	(*NodeListResp)(nil),   // 6: NodeListResp
}
var file_nodes_proto_depIdxs = []int32{
	5, // 0: NodeListResp.list:type_name -> NodeInfo
	0, // 1: Node.Edit:input_type -> NodeEditReq
	2, // 2: Node.Delete:input_type -> NodeDeleteReq
	4, // 3: Node.List:input_type -> NodeListReq
	1, // 4: Node.Edit:output_type -> NodeEditResp
	3, // 5: Node.Delete:output_type -> NodeDeleteResp
	6, // 6: Node.List:output_type -> NodeListResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nodes_proto_init() }
func file_nodes_proto_init() {
	if File_nodes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodes_proto_rawDesc), len(file_nodes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodes_proto_goTypes,
		DependencyIndexes: file_nodes_proto_depIdxs,
		MessageInfos:      file_nodes_proto_msgTypes,
	}.Build()
	File_nodes_proto = out.File
	file_nodes_proto_goTypes = nil
	file_nodes_proto_depIdxs = nil
}
